# Generated by Django 5.1.5 on 2025-02-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
    ]
