# Generated by Django 5.1.5 on 2025-02-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_address_remove_place_slider_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='preview_photo',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
    ]
