# Generated by Django 5.1.5 on 2025-02-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_promotioncondition_place_promotion_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='promotion_conditions',
        ),
        migrations.CreateModel(
            name='PlacePromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_text', models.CharField(max_length=255)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_conditions', to='places.place')),
            ],
        ),
        migrations.DeleteModel(
            name='PromotionCondition',
        ),
    ]
